DATA:
  name: "FreiHAND"
  img_size: 64
  num_classes: 43
MODEL:
  g_cond_mtd: "SPADE"
  d_cond_mtd: "CAT"
  z_dim: 21
LOSS:
  adv_loss: "hinge"
  cond_lambda: 1.0
OPTIMIZATION:
  batch_size: 64
  total_steps: 10000
